// @ts-check
/**
 * Generate the content contract's two derived artefacts from `src/types.ts`, so neither can drift
 * from the types:
 *
 * 1. `schema/site-content.schema.json` — JSON Schema (draft-07) for `LocalContent`, every other
 *    content type a named definition. Shipped on the `./schema` subpath for non-TypeScript tools
 *    (the generator, the hub's seed command).
 * 2. `src/generated/validators.ts` — that schema compiled by Ajv into standalone code, which
 *    `src/validate.ts` wraps. Compiling here rather than at runtime keeps the published package free
 *    of runtime dependencies.
 *
 *   node scripts/build-schema.mjs           write both
 *   node scripts/build-schema.mjs --check   fail if either differs from what is committed
 *
 * `Photo` is the one type rewritten after generation. In TypeScript it is `ImageMetadata |
 * RemotePhoto`, and `ImageMetadata` is Astro's — a schema that described it would tie every
 * non-Astro tool to Astro's internals. A content file only ever holds `{ src, width, height }` (a
 * remote URL, or a basename with zero dimensions before upload), so that is what the schema says.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createGenerator } from 'ts-json-schema-generator'
import AjvModule from 'ajv'
import standaloneModule from 'ajv/dist/standalone/index.js'

// CommonJS modules whose `module.exports` is also their `.default`; typed as the latter.
const Ajv = AjvModule.default
const standaloneCode = standaloneModule.default

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SCHEMA_FILE = resolve(ROOT, 'schema/site-content.schema.json')
const VALIDATORS_FILE = resolve(ROOT, 'src/generated/validators.ts')
export const SCHEMA_ID = 'https://github.com/johncaden124/holland-sites-cms/schema/site-content.schema.json'

/** Definitions `validateSiteContent({ root })` can validate against, besides the whole document. */
export const ROOTS = [
  'LocalContent',
  'SiteContent',
  'SiteSettings',
  'Service',
  'GalleryImage',
  'Testimonial',
  'ProcessStep',
  'Stat',
  'Faq',
]

function buildSchema() {
  const schema = /** @type {any} */ (
    createGenerator({
      path: resolve(ROOT, 'src/types.ts'),
      tsconfig: resolve(ROOT, 'tsconfig.json'),
      type: 'LocalContent',
      skipTypeCheck: true,
      additionalProperties: false,
      sortProps: false,
    }).createSchema('LocalContent')
  )
  const defs = schema.definitions
  defs.Photo = {
    description:
      'An image: an absolute media URL with its intrinsic size, or — in a content file before upload — a basename with zero dimensions.',
    type: 'object',
    properties: {
      src: { type: 'string' },
      width: { type: 'number', minimum: 0 },
      height: { type: 'number', minimum: 0 },
    },
    required: ['src', 'width', 'height'],
  }
  for (const astroOnly of ['ImageMetadata', 'ImageInputFormat', 'RemotePhoto']) delete defs[astroOnly]
  const text = JSON.stringify(schema)
  if (/ImageMetadata|ImageInputFormat|RemotePhoto/.test(text)) {
    throw new Error('build-schema: an Astro image type is still referenced after rewriting Photo')
  }
  return { $id: SCHEMA_ID, ...schema }
}

/** @param {any} schema */
function buildValidators(schema) {
  const ajv = new Ajv({ allErrors: true, inlineRefs: false, code: { source: true, esm: true }, strict: true })
  ajv.addSchema(schema)
  const refs = Object.fromEntries(ROOTS.map((name) => [name, `${SCHEMA_ID}#/definitions/${name}`]))
  const code = standaloneCode(ajv, refs)
  if (/require\(|from "ajv/.test(code)) {
    throw new Error('build-schema: the compiled validators import Ajv at runtime — avoid the keyword that needs it')
  }
  return `// @ts-nocheck\n// Generated by scripts/build-schema.mjs from src/types.ts — do not edit.\n${code}\n`
}

const schema = buildSchema()
const outputs = [
  [SCHEMA_FILE, JSON.stringify(schema, null, 2) + '\n'],
  [VALIDATORS_FILE, buildValidators(schema)],
]

if (process.argv.includes('--check')) {
  const stale = outputs.filter(([file, text]) => !existsSync(file) || readFileSync(file, 'utf8') !== text)
  if (stale.length) {
    console.error(
      `build-schema: out of date: ${stale.map(([f]) => f.replace(`${ROOT}/`, '')).join(', ')} — run npm run schema and commit`,
    )
    process.exit(1)
  }
  console.log('build-schema: schema/ and src/generated/ are up to date')
} else {
  for (const [file, text] of outputs) {
    mkdirSync(dirname(file), { recursive: true })
    writeFileSync(file, text)
  }
}
